config/routes.rb
Rails.application.routes.draw do
  
  get 'challenges/new'

  get 'challenges/index'

  get 'challenges/show'

  get 'challenges/edit'

  devise_for :users
  root 'users#new'

  resources :users

end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 #    has_secure_password
	# validates_confirmation_of :password
	# validates_prescence_of :password, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:fname, :ffc, :fid, :password, :email, :alias, :password_confirmation) }
  end
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  def new
  	@challenge = Challenge.new
  end

  def index
    @challenges = Challenge.all
  end

  def show
	@challenges = Challenge.all
    else
    @challenge = Challenge.find(params[:id])
  end

  def edit

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show, :destroy]
  def index
    @users = User.all
  end

  def edit
  end

  def show
    @user = User.all
    else
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def destroy
    @user.destroy
    redirect_to @user, notice: "User deleted"
  end

  def create
    @user = User.new(user_params)
      if @user.save
        redirect_to @user, notice: "User successfully created"
      else
        render :new
  end
end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "User successfully updated"
    else
      render :edit
  end
end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:fname, :alias, :fid, :ffc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/views/challenges/_form.html.erb
<%= form_for @challenges do |f| %>
    <%= f.label :date %>
    <%= f.date_field :date %><br />
    
    <%= f.label :time %>
    <%= f.datetime_field :time %><br />
    
    <%= f.label :message_box %>
    <%= f.text_area :message_box %><br />
    
    <%= f.submit %>
<% end %>

app/views/challenges/edit.html.erb
<h1>Challenges#edit</h1>
<p>Find me in app/views/challenges/edit.html.erb</p>

app/views/challenges/index.html.erb
<h1>Challenges#index</h1>
<p>Find me in app/views/challenges/index.html.erb</p>

app/views/challenges/new.html.erb
<h1>Challenges#new</h1>
<p>Find me in app/views/challenges/new.html.erb</p>

app/views/challenges/show.html.erb
<h1>Challenges#show</h1>
<p>Find me in app/views/challenges/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Smashzone</title>
  <!-- Google font import -->
  <link href='http://fonts.googleapis.com/css?family=Permanent+Marker' rel='stylesheet' type='text/css'>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
		<nav class='navbar navbar-default'>
			<h2 class="logo">Smashzone!</h2>
				<div class="btn-group" role="group" aria-label="...">
				  <button type="button" class="btn-group-lg"><%= link_to 'Home', root_path %></button>
				  <button type="button" class="btn-group-lg"><%= link_to 'Smashers', users_path %></button>
				  <button type="button" class="btn-group-lg"><%= link_to 'Edit Profile', edit_user_registration_path %></button>
				  <button type="button" class="btn-group-lg"><%= link_to 'Log out', destroy_user_session_path %></button>
				</div>
		</nav>
	<div class="container page-wrap">
				
		<% if flash[:notice] %>
			<p class="notice"><%= notice %></p>
		<% end %>

		<% if flash[:alert] %>
	    	<p class="alert"><%= alert %></p>
		<% end %>

		<%= yield %>
	</div>
	<nav class='navbar navbar-default navbar-fixed-bottom'>
		<h3> Follow us on Facebook and/or Twitter! </h3>
	</nav>
</body>
</html>

app/views/users/_form.html.erb
# <%= form_for @challenges do |f| %>
#     <%= f.label :date %>
#     <%= f.date_field :date %><br />
    
#     <%= f.label :time %>
#     <%= f.datetime_field :time %><br />
    
#     <%= f.label :message_box %>
#     <%= f.text_area :message_box %><br />
    
#     <%= f.submit %>
# <% end %>

app/views/users/edit.html.erb
<h1>Create#edit</h1>
<p>Find me in app/views/create/edit.html.erb</p>

app/views/users/index.html.erb
<% @users.each do |user| %>
<div class='user well'>
  <h3>Full name:<br/><%= user.fname %></h3>
  <h3>Alias:<br/><%=user.alias %></h3>
  <h3>Friend Code:<br/><%= user.ffc %></h3>
  <h3>Nintendo Network Id:<br/><%= user.fid %></h3>
  <div class="btn-group" role="group" aria-label="...">
    <button type="button" class="btn-group-lg"><%= link_to 'Challenge me', challenges_new_path %></button>
  </div>
</div>
<% end %>

app/views/users/new.html.erb
<div class='container-fluid'>
	<div class='row'>
		<div class='col-md-8'>
			<div class="intro">
				<h4>
					Smashzone is a site dedicated to helping the competitive smash brothers community be more connected. With this service, you can create a user profile and find other competitive smash players in your area and challenge them to a match!
				</h4>
			</div>
		</div>
	</div>
	<div class='row'>
		<div class='col-md-8'>
			<% unless user_signed_in? %>
				<%= render '/devise/registrations/new' %>
			<% else %>
			<%= link_to 'sign out', destroy_user_session_path %>
			<% end %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<h1>Specified User</h1>
<div class='container-fluid'>
<div class='col-md-8'>
	<h3>Full name:<%= @user.fname %></h3>
	<h3>Alias:<%=@user.alias %></h3>
	<h3>Friend Code:<%= @user.ffc %></h3>
	<h3>Nintendo Network Id:<%= @user.fid %></h3>
	<p>This is a profile</p>
</div>
</div>